#!/bin/sh
# postinst script for openacalendar
#
# see: dh_installdeb(1)

[ -n "${DEBUG}" ] && set -x
set -e

. /usr/share/debconf/confmodule

LOGFILE='/var/log/openacalendar_install.log'
HOME=/usr/share/openacalendar

# if this script aborts with an error dpkg can hang if a debconf can
# hang if daemons have been started
trap db_stop EXIT

# Add the "openacalendar" user and group
getent group openacalendar >/dev/null || groupadd -r openacalendar
getent passwd openacalendar >/dev/null || \
    useradd -r -g openacalendar -d /usr/share/openacalendar -s /usr/sbin/nologin -c "OpenACalendar" openacalendar

chown -Rf openacalendar:openacalendar '/var/lib/openacalendar'
chown -Rf openacalendar:openacalendar '/var/cache/openacalendar'
chmod 755 '/var/lib/openacalendar'
chmod 755 '/var/cache/openacalendar'

# Site Config (needs better logic to handle upgrades & SSL)
sed -i "s/webIndexDomain = .*/webIndexDomain = 'www.`hostname -f`';/" /etc/openacalendar/config.php
sed -i "s/webSiteDomain = .*/webSiteDomain = '`hostname -f`';/" /etc/openacalendar/config.php
sed -i "s/webCommonSessionDomain = .*/webCommonSessionDomain = '`hostname -f`';/" /etc/openacalendar/config.php

sed -i "s/ServerName REPLACEME/ServerName `hostname -f`/" /etc/apache2/sites-available/05-openacalendar.conf
sed -i "s/ServerAdmin REPLACEME/ServerAdmin `hostname -f`/" /etc/apache2/sites-available/05-openacalendar.conf
a2enmod rewrite
a2ensite 05-openacalendar.conf
echo "Restart Apache2 to enable OpenACalendar"

# DBConfig
. /usr/share/dbconfig-common/dpkg/postinst
dbc_generate_include='php:/etc/openacalendar/dbconfig.php'
dbc_generate_include_owner='www-data'
dbc_go openacalendar $@

# Own all the core files
chown -Rf openacalendar:openacalendar $HOME

#DEBHELPER#

exit 0
