#!/bin/sh

[ -n "${DEBUG}" ] && set -x
set -e

if [ -f /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
fi

case "$1" in
	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

	purge)
		if [ -f /usr/share/dbconfig-common/dpkg/postrm ]; then
			. /usr/share/dbconfig-common/dpkg/postrm
			db_purge
		fi
		if which ucf >/dev/null 2>&1; then
			ucf --debconf-ok --purge /etc/openacalendar/config.php
		fi
		# package-generated or runtime files are removed
		rm -rf /var/cache/openacalendar
		rm -rf /etc/openacalendar
	;;
	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
